[package]
name = "schnorr"
version = "0.1.0"
authors = ["kev <decentralisedkev@gmail.com>"]
edition = "2018"

[dependencies.curve25519-dalek]
version = "1"
features = ["nightly"]


[dependencies]
rand_os = "0.1.0"
sha2 = "0.8"